/**
 * Phase 1B — Milestone Readiness evaluator.
 *
 * Pure, dependency-light. Derives every gate on the Project Spine's
 * Milestone Readiness matrix from durable project records instead of
 * inferring them from milestone `phase` / `status` labels.
 *
 * Gates:
 *
 *   criteria     — engine_milestones.acceptance_criteria + approval_status.
 *                  empty acceptance_criteria → not_configured.
 *                  approved → done · rejected → blocked ·
 *                  pending / needs_review → review · else not_started.
 *
 *   design       — engine_project_frames scoped to this milestone.
 *                  approved frame → done · any frame → review ·
 *                  none → not_configured.
 *
 *   mockups      — engine_project_mockups scoped to this milestone.
 *                  approved mockup → done · any mockup → review ·
 *                  none → not_configured.
 *
 *   build        — engine_project_build_packets scoped to this milestone.
 *                  all packets accepted → done · any packet → in_progress ·
 *                  none → not_configured.
 *
 *   evidence     — engine_project_build_evidence tied to those packets.
 *                  any evidence → done ·
 *                  packets exist but no evidence → not_started ·
 *                  no packets → not_configured.
 *
 *   qa_auto      — engine_project_qa_evidence_reviews generated by AI /
 *                  Openclaw (generated_by = 'ai' | 'openclaw' OR
 *                  openclaw_run_id set).
 *                  pass verdict → done · any → review ·
 *                  none → not_configured.
 *
 *   qa_human     — engine_project_qa_evidence_reviews recorded by a human
 *                  (generated_by = 'human' OR neither ai nor openclaw_run_id).
 *                  pass verdict → done · any → review ·
 *                  none → not_configured.
 *
 *   due_date     — engine_milestones.due_date presence.
 *                  set → done · missing → not_configured.
 *
 *   dependencies — engine_milestones.dependencies jsonb.
 *                  empty / null → not_configured.
 *                  every entry marked satisfied/done/approved → done ·
 *                  else review.
 *
 *   blockers     — engine_milestones.status.
 *                  blocked → blocked · else done ("no blockers").
 *
 * Rule of thumb: absence of a backing record for a gate that expects one
 * renders `not_configured`; presence without any progress-of-work signal
 * renders `not_started`.
 *
 * NO DB calls. NO React. Safe to import from server functions, route
 * components, and unit tests.
 */

export type MilestoneGateState =
  | "done"
  | "review"
  | "in_progress"
  | "blocked"
  | "not_started"
  | "not_configured"
  | "not_applicable";

export type MilestoneGates = {
  criteria: MilestoneGateState;
  design: MilestoneGateState;
  mockups: MilestoneGateState;
  build: MilestoneGateState;
  evidence: MilestoneGateState;
  qa_auto: MilestoneGateState;
  qa_human: MilestoneGateState;
  due_date: MilestoneGateState;
  dependencies: MilestoneGateState;
  blockers: MilestoneGateState;
};

export type MilestoneInput = {
  status?: string | null;
  approval_status?: string | null;
  due_date?: string | null;
  acceptance_criteria?: unknown;
  dependencies?: unknown;
  /**
   * When explicitly false, the mockups gate is N/A unless mockup records
   * exist. Undefined / true keeps the default behaviour (records drive it,
   * absence → not_configured).
   */
  mockups_required?: boolean | null;
};

export type FrameLike = { status?: string | null; approved_at?: string | null };
export type MockupLike = { status?: string | null; approved_at?: string | null };
export type PacketLike = {
  status?: string | null;
  accepted_at?: string | null;
  handed_off_at?: string | null;
};
export type EvidenceLike = { evidence_type?: string | null };
export type QaPlanLike = { status?: string | null; approved_at?: string | null };
export type QaReviewLike = {
  status?: string | null;
  verdict?: string | null;
  approved_at?: string | null;
  generated_by?: string | null;
  openclaw_run_id?: string | null;
};

export type MilestoneDurableRecords = {
  frames: readonly FrameLike[];
  mockups: readonly MockupLike[];
  packets: readonly PacketLike[];
  evidence: readonly EvidenceLike[];
  qa_plans: readonly QaPlanLike[];
  qa_reviews: readonly QaReviewLike[];
};

const APPROVED_STATUSES = new Set(["approved", "accepted", "done", "completed", "satisfied"]);
const PASS_VERDICTS = new Set(["pass", "passed", "approved", "accepted", "ok"]);
const AUTO_GENERATORS = new Set(["ai", "openclaw", "automation", "system"]);

function isApprovedFrame(f: FrameLike): boolean {
  return APPROVED_STATUSES.has(String(f.status ?? "").toLowerCase()) || Boolean(f.approved_at);
}
function isAcceptedPacket(p: PacketLike): boolean {
  const s = String(p.status ?? "").toLowerCase();
  return APPROVED_STATUSES.has(s) || Boolean(p.accepted_at);
}
function isPassedReview(r: QaReviewLike): boolean {
  const s = String(r.status ?? "").toLowerCase();
  const v = String(r.verdict ?? "").toLowerCase();
  return PASS_VERDICTS.has(v) || APPROVED_STATUSES.has(s) || Boolean(r.approved_at);
}
function isAutoReview(r: QaReviewLike): boolean {
  const g = String(r.generated_by ?? "").toLowerCase();
  if (AUTO_GENERATORS.has(g)) return true;
  return Boolean(r.openclaw_run_id);
}
function isHumanReview(r: QaReviewLike): boolean {
  return !isAutoReview(r);
}

function nonEmpty(value: unknown): boolean {
  if (value == null) return false;
  if (Array.isArray(value)) return value.length > 0;
  if (typeof value === "string") return value.trim().length > 0;
  if (typeof value === "object") return Object.keys(value as object).length > 0;
  return true;
}

function dependencyEntries(value: unknown): unknown[] {
  if (Array.isArray(value)) return value;
  if (value && typeof value === "object") {
    const rec = value as Record<string, unknown>;
    for (const k of ["items", "list", "dependencies"]) {
      const v = rec[k];
      if (Array.isArray(v)) return v;
    }
    return Object.values(rec);
  }
  return [];
}

function isSatisfiedDep(entry: unknown): boolean {
  if (entry == null) return false;
  if (typeof entry === "string") return false;
  if (typeof entry === "object") {
    const r = entry as Record<string, unknown>;
    for (const k of ["status", "state", "resolution"]) {
      const v = r[k];
      if (typeof v === "string" && APPROVED_STATUSES.has(v.toLowerCase())) return true;
    }
    for (const k of ["satisfied", "resolved", "done", "complete", "completed"]) {
      if (r[k] === true) return true;
    }
  }
  return false;
}

export function deriveMilestoneGatesFromRecords(
  milestone: MilestoneInput,
  records: MilestoneDurableRecords,
): MilestoneGates {
  const isBlocked = String(milestone.status ?? "").toLowerCase() === "blocked";
  const approval = String(milestone.approval_status ?? "").toLowerCase();

  // Criteria — acceptance_criteria jsonb + approval_status
  let criteria: MilestoneGateState;
  if (!nonEmpty(milestone.acceptance_criteria)) {
    criteria = "not_configured";
  } else if (approval === "approved") {
    criteria = "done";
  } else if (approval === "rejected") {
    criteria = "blocked";
  } else if (approval === "pending" || approval === "needs_review") {
    criteria = "review";
  } else {
    criteria = "not_started";
  }

  // Design (frames)
  let design: MilestoneGateState;
  const anyFrame = records.frames.length > 0;
  const designDone = records.frames.some(isApprovedFrame);
  if (isBlocked && !designDone && anyFrame) design = "blocked";
  else if (designDone) design = "done";
  else if (anyFrame) design = "review";
  else design = "not_configured";

  // Mockups
  let mockups: MilestoneGateState;
  const anyMockup = records.mockups.length > 0;
  const mockupsDone = records.mockups.some(isApprovedFrame);
  const mockupsRequired = milestone.mockups_required !== false;
  if (!anyMockup && !mockupsRequired) mockups = "not_applicable";
  else if (isBlocked && !mockupsDone && anyMockup) mockups = "blocked";
  else if (mockupsDone) mockups = "done";
  else if (anyMockup) mockups = "review";
  else mockups = "not_configured";

  // Build
  let build: MilestoneGateState;
  const anyPacket = records.packets.length > 0;
  const buildDone = anyPacket && records.packets.every(isAcceptedPacket);
  if (isBlocked && !buildDone && anyPacket) build = "blocked";
  else if (buildDone) build = "done";
  else if (anyPacket) build = "in_progress";
  else build = "not_configured";

  // Evidence — separate from build
  let evidence: MilestoneGateState;
  const anyEvidence = records.evidence.length > 0;
  if (anyEvidence) evidence = "done";
  else if (anyPacket) evidence = "not_started";
  else evidence = "not_configured";

  // Automated QA
  const autoReviews = records.qa_reviews.filter(isAutoReview);
  let qa_auto: MilestoneGateState;
  if (autoReviews.some(isPassedReview)) qa_auto = "done";
  else if (autoReviews.length > 0) qa_auto = "review";
  else qa_auto = "not_configured";

  // Human QA
  const humanReviews = records.qa_reviews.filter(isHumanReview);
  let qa_human: MilestoneGateState;
  if (humanReviews.some(isPassedReview)) qa_human = "done";
  else if (humanReviews.length > 0 || records.qa_plans.length > 0) qa_human = "review";
  else qa_human = "not_configured";

  // Due date
  const due_date: MilestoneGateState = milestone.due_date ? "done" : "not_configured";

  // Dependencies
  let dependencies: MilestoneGateState;
  const deps = dependencyEntries(milestone.dependencies);
  if (deps.length === 0) dependencies = "not_configured";
  else if (deps.every(isSatisfiedDep)) dependencies = "done";
  else dependencies = "review";

  // Blockers — done ("no blockers") vs blocked
  const blockers: MilestoneGateState = isBlocked ? "blocked" : "done";

  // ---------- Predecessor ordering ----------
  //
  // Downstream completion cannot appear before required predecessors.
  // Chain:  criteria → mockups (if required) → build → evidence → QA
  //
  // A gate is "satisfied" for ordering when its state is `done` or
  // `not_applicable`. Anything else means the predecessor is incomplete
  // and downstream `done` must be downgraded so the UI cannot claim work
  // finished ahead of its prerequisites.
  const satisfied = (s: MilestoneGateState) => s === "done" || s === "not_applicable";
  const cap = (s: MilestoneGateState): MilestoneGateState => {
    // Only downgrade completion signals. Preserve blocked / not_applicable
    // and keep in-flight signals visible.
    if (s === "done") return "review";
    if (s === "in_progress") return "in_progress";
    return s;
  };

  if (!satisfied(criteria)) {
    mockups = cap(mockups);
    build = cap(build);
    evidence = cap(evidence);
    qa_auto = cap(qa_auto);
    qa_human = cap(qa_human);
  }
  if (!satisfied(mockups)) {
    build = cap(build);
    evidence = cap(evidence);
    qa_auto = cap(qa_auto);
    qa_human = cap(qa_human);
  }
  if (!satisfied(build)) {
    evidence = cap(evidence);
    qa_auto = cap(qa_auto);
    qa_human = cap(qa_human);
  }
  if (!satisfied(evidence)) {
    qa_auto = cap(qa_auto);
    qa_human = cap(qa_human);
  }

  return {
    criteria,
    design,
    mockups,
    build,
    evidence,
    qa_auto,
    qa_human,
    due_date,
    dependencies,
    blockers,
  };
}

/**
 * Payload-shape helper used by the server to scope project-scoped rows to
 * a single milestone. Kept alongside the evaluator so tests can lock the
 * shape down.
 */
export function payloadMatchesMilestone(
  payload: unknown,
  milestoneId: string,
): boolean {
  if (!payload || typeof payload !== "object") return false;
  const p = payload as Record<string, unknown>;
  if (p.milestone_id === milestoneId) return true;
  if (p.milestoneId === milestoneId) return true;
  const arr = p.milestone_ids;
  if (Array.isArray(arr) && (arr as unknown[]).includes(milestoneId)) return true;
  return false;
}
