/* eslint-disable @typescript-eslint/no-explicit-any */
import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { MilestoneTabs } from "@/components/engine/MilestoneTabs";
import { getMilestoneQa } from "@/lib/engine-milestone-workspace.functions";
import { ShieldCheck } from "lucide-react";

export const Route = createFileRoute(
  "/engine/projects/$projectId/milestones/$milestoneId/qa",
)({
  component: MilestoneQaPage,
  errorComponent: ({ error }) => (
    <div className="p-4 text-sm text-red-700">Failed: {(error as Error).message}</div>
  ),
});

function MilestoneQaPage() {
  const { projectId, milestoneId } = Route.useParams();
  const fetchFn = useServerFn(getMilestoneQa);
  const q = useQuery({
    queryKey: ["engine", "milestone-qa", projectId, milestoneId],
    queryFn: () => fetchFn({ data: { projectId, milestoneId } }),
    staleTime: 60_000,
  });

  const data = q.data as
    | {
        milestone: any;
        plans: any[];
        reviews: any[];
        total_plans_in_project: number;
        total_reviews_in_project: number;
      }
    | undefined;

  return (
    <div className="space-y-4">
      <MilestoneTabs
        projectId={projectId}
        milestoneId={milestoneId}
        milestoneName={data?.milestone?.name ?? null}
      />

      {q.isPending ? (
        <div className="text-sm text-[#667085]">Loading QA…</div>
      ) : q.isError ? (
        <div className="text-sm text-red-700">{(q.error as Error).message}</div>
      ) : !data || (data.plans.length === 0 && data.reviews.length === 0) ? (
        <section className="rounded-2xl border border-dashed border-[#E8E1D6] bg-white p-8 text-center">
          <ShieldCheck className="mx-auto h-8 w-8 text-[#667085]" />
          <div className="mt-3 font-display text-lg text-[#0A0F1F]">No QA yet</div>
          <p className="mx-auto mt-1 max-w-md text-sm text-[#667085]">
            When a QA plan or evidence review is generated for this milestone,
            it will appear here with verdicts and approver attribution.
          </p>
          {data && (data.total_plans_in_project > 0 || data.total_reviews_in_project > 0) ? (
            <p className="mt-2 text-xs text-[#667085]">
              {data.total_plans_in_project} plan
              {data.total_plans_in_project === 1 ? "" : "s"} · {data.total_reviews_in_project} review
              {data.total_reviews_in_project === 1 ? "" : "s"} in project (untagged).
            </p>
          ) : null}
        </section>
      ) : (
        <>
          {data.plans.length ? (
            <section className="rounded-2xl border border-[#E8E1D6] bg-white shadow-sm">
              <div className="border-b border-[#E8E1D6] px-5 py-3 font-mono text-[10px] uppercase tracking-[0.22em] text-[#667085]">
                QA plans ({data.plans.length})
              </div>
              <ul className="divide-y divide-[#F3EEE6]">
                {data.plans.map((p) => (
                  <li key={p.id} className="px-5 py-4">
                    <div className="flex items-baseline justify-between gap-3">
                      <div className="font-display text-base text-[#0A0F1F]">{p.title}</div>
                      <span className="rounded-full border border-[#E8E1D6] px-2 py-0.5 font-mono text-[10px] uppercase tracking-[0.18em] text-[#667085]">
                        {p.status}
                      </span>
                    </div>
                    {p.summary ? (
                      <p className="mt-1 text-sm text-[#3f4a63]">{p.summary}</p>
                    ) : null}
                    <div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-[11px] text-[#667085]">
                      {p.generated_by ? <span>Generated by · {p.generated_by}</span> : null}
                      {p.approved_at ? (
                        <span>Approved · {new Date(p.approved_at).toLocaleString()}</span>
                      ) : null}
                    </div>
                  </li>
                ))}
              </ul>
            </section>
          ) : null}

          {data.reviews.length ? (
            <section className="rounded-2xl border border-[#E8E1D6] bg-white shadow-sm">
              <div className="border-b border-[#E8E1D6] px-5 py-3 font-mono text-[10px] uppercase tracking-[0.22em] text-[#667085]">
                Evidence reviews ({data.reviews.length})
              </div>
              <ul className="divide-y divide-[#F3EEE6]">
                {data.reviews.map((r) => (
                  <li key={r.id} className="px-5 py-4">
                    <div className="flex items-baseline justify-between gap-3">
                      <div className="font-display text-base text-[#0A0F1F]">{r.title}</div>
                      <div className="flex items-center gap-2">
                        {r.verdict ? (
                          <span className="rounded-full border border-[#E8E1D6] bg-[#FBF9F4] px-2 py-0.5 font-mono text-[10px] uppercase tracking-[0.18em] text-[#3f4a63]">
                            {r.verdict}
                          </span>
                        ) : null}
                        <span className="rounded-full border border-[#E8E1D6] px-2 py-0.5 font-mono text-[10px] uppercase tracking-[0.18em] text-[#667085]">
                          {r.status}
                        </span>
                      </div>
                    </div>
                    {r.summary ? (
                      <p className="mt-1 text-sm text-[#3f4a63]">{r.summary}</p>
                    ) : null}
                    {r.rejected_reason ? (
                      <p className="mt-1 text-xs text-[#a4283c]">Rejected · {r.rejected_reason}</p>
                    ) : null}
                    <div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-[11px] text-[#667085]">
                      {r.approved_at ? (
                        <span>Approved · {new Date(r.approved_at).toLocaleString()}</span>
                      ) : null}
                    </div>
                  </li>
                ))}
              </ul>
            </section>
          ) : null}
        </>
      )}
    </div>
  );
}
