/* eslint-disable @typescript-eslint/no-explicit-any */
import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { MilestoneTabs } from "@/components/engine/MilestoneTabs";
import { getMilestoneMockups } from "@/lib/engine-milestone-workspace.functions";
import { Image as ImageIcon } from "lucide-react";

export const Route = createFileRoute(
  "/engine/projects/$projectId/milestones/$milestoneId/mockups",
)({
  component: MilestoneMockupsPage,
  errorComponent: ({ error }) => (
    <div className="p-4 text-sm text-red-700">Failed: {(error as Error).message}</div>
  ),
  notFoundComponent: () => (
    <div className="p-4 text-sm text-[#667085]">Milestone not found.</div>
  ),
});

function MilestoneMockupsPage() {
  const { projectId, milestoneId } = Route.useParams();
  const fetchFn = useServerFn(getMilestoneMockups);
  const q = useQuery({
    queryKey: ["engine", "milestone-mockups", projectId, milestoneId],
    queryFn: () => fetchFn({ data: { projectId, milestoneId } }),
    staleTime: 60_000,
  });

  const data = q.data as
    | { milestone: any; mockups: any[]; total_in_project: number }
    | undefined;

  return (
    <div className="space-y-4">
      <MilestoneTabs
        projectId={projectId}
        milestoneId={milestoneId}
        milestoneName={data?.milestone?.name ?? null}
      />

      {q.isPending ? (
        <div className="text-sm text-[#667085]">Loading mockups…</div>
      ) : q.isError ? (
        <div className="text-sm text-red-700">{(q.error as Error).message}</div>
      ) : !data || data.mockups.length === 0 ? (
        <section className="rounded-2xl border border-dashed border-[#E8E1D6] bg-white p-8 text-center">
          <ImageIcon className="mx-auto h-8 w-8 text-[#667085]" />
          <div className="mt-3 font-display text-lg text-[#0A0F1F]">No mockups yet</div>
          <p className="mx-auto mt-1 max-w-md text-sm text-[#667085]">
            No mockup versions have been generated for this milestone. Once the
            mockup builder produces a version, it will appear here with its
            approval status.
          </p>
          {data && data.total_in_project > 0 ? (
            <p className="mt-2 text-xs text-[#667085]">
              {data.total_in_project} project-level mockup
              {data.total_in_project === 1 ? "" : "s"} not tagged to this milestone.
            </p>
          ) : null}
        </section>
      ) : (
        <section className="rounded-2xl border border-[#E8E1D6] bg-white shadow-sm">
          <div className="border-b border-[#E8E1D6] px-5 py-3 font-mono text-[10px] uppercase tracking-[0.22em] text-[#667085]">
            Mockup versions ({data.mockups.length})
          </div>
          <ul className="divide-y divide-[#F3EEE6]">
            {data.mockups.map((m) => (
              <li key={m.id} className="px-5 py-4">
                <div className="flex items-baseline justify-between gap-3">
                  <div className="font-display text-base text-[#0A0F1F]">{m.title}</div>
                  <span className="rounded-full border border-[#E8E1D6] px-2 py-0.5 font-mono text-[10px] uppercase tracking-[0.18em] text-[#667085]">
                    {m.status}
                  </span>
                </div>
                {m.summary ? (
                  <p className="mt-1 text-sm text-[#3f4a63]">{m.summary}</p>
                ) : null}
                <div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-[11px] text-[#667085]">
                  <span>Generated by · {m.generated_by ?? "—"}</span>
                  <span>Created · {new Date(m.created_at).toLocaleString()}</span>
                  {m.approved_at ? (
                    <span>Approved · {new Date(m.approved_at).toLocaleString()}</span>
                  ) : null}
                </div>
              </li>
            ))}
          </ul>
        </section>
      )}
    </div>
  );
}
