/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatWeBuildRouteImport } from './routes/what-we-build'
import { Route as WalksRouteImport } from './routes/walks'
import { Route as InvestmentRouteImport } from './routes/investment'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as BuildMyRoadmapRouteImport } from './routes/build-my-roadmap'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WalksSlugRouteImport } from './routes/walks_.$slug'
import { Route as InsightsSlugRouteImport } from './routes/insights_.$slug'

const WhatWeBuildRoute = WhatWeBuildRouteImport.update({
  id: '/what-we-build',
  path: '/what-we-build',
  getParentRoute: () => rootRouteImport,
} as any)
const WalksRoute = WalksRouteImport.update({
  id: '/walks',
  path: '/walks',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentRoute = InvestmentRouteImport.update({
  id: '/investment',
  path: '/investment',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildMyRoadmapRoute = BuildMyRoadmapRouteImport.update({
  id: '/build-my-roadmap',
  path: '/build-my-roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalksSlugRoute = WalksSlugRouteImport.update({
  id: '/walks_/$slug',
  path: '/walks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/insights_/$slug',
  path: '/insights/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/build-my-roadmap': typeof BuildMyRoadmapRoute
  '/insights': typeof InsightsRoute
  '/investment': typeof InvestmentRoute
  '/walks': typeof WalksRoute
  '/what-we-build': typeof WhatWeBuildRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/walks/$slug': typeof WalksSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/build-my-roadmap': typeof BuildMyRoadmapRoute
  '/insights': typeof InsightsRoute
  '/investment': typeof InvestmentRoute
  '/walks': typeof WalksRoute
  '/what-we-build': typeof WhatWeBuildRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/walks/$slug': typeof WalksSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/build-my-roadmap': typeof BuildMyRoadmapRoute
  '/insights': typeof InsightsRoute
  '/investment': typeof InvestmentRoute
  '/walks': typeof WalksRoute
  '/what-we-build': typeof WhatWeBuildRoute
  '/insights_/$slug': typeof InsightsSlugRoute
  '/walks_/$slug': typeof WalksSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/build-my-roadmap'
    | '/insights'
    | '/investment'
    | '/walks'
    | '/what-we-build'
    | '/insights/$slug'
    | '/walks/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/build-my-roadmap'
    | '/insights'
    | '/investment'
    | '/walks'
    | '/what-we-build'
    | '/insights/$slug'
    | '/walks/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/build-my-roadmap'
    | '/insights'
    | '/investment'
    | '/walks'
    | '/what-we-build'
    | '/insights_/$slug'
    | '/walks_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BuildMyRoadmapRoute: typeof BuildMyRoadmapRoute
  InsightsRoute: typeof InsightsRoute
  InvestmentRoute: typeof InvestmentRoute
  WalksRoute: typeof WalksRoute
  WhatWeBuildRoute: typeof WhatWeBuildRoute
  InsightsSlugRoute: typeof InsightsSlugRoute
  WalksSlugRoute: typeof WalksSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/what-we-build': {
      id: '/what-we-build'
      path: '/what-we-build'
      fullPath: '/what-we-build'
      preLoaderRoute: typeof WhatWeBuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/walks': {
      id: '/walks'
      path: '/walks'
      fullPath: '/walks'
      preLoaderRoute: typeof WalksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investment': {
      id: '/investment'
      path: '/investment'
      fullPath: '/investment'
      preLoaderRoute: typeof InvestmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build-my-roadmap': {
      id: '/build-my-roadmap'
      path: '/build-my-roadmap'
      fullPath: '/build-my-roadmap'
      preLoaderRoute: typeof BuildMyRoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/walks_/$slug': {
      id: '/walks_/$slug'
      path: '/walks/$slug'
      fullPath: '/walks/$slug'
      preLoaderRoute: typeof WalksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights_/$slug': {
      id: '/insights_/$slug'
      path: '/insights/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BuildMyRoadmapRoute: BuildMyRoadmapRoute,
  InsightsRoute: InsightsRoute,
  InvestmentRoute: InvestmentRoute,
  WalksRoute: WalksRoute,
  WhatWeBuildRoute: WhatWeBuildRoute,
  InsightsSlugRoute: InsightsSlugRoute,
  WalksSlugRoute: WalksSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
