/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatWeBuildRouteImport } from './routes/what-we-build'
import { Route as WalksRouteImport } from './routes/walks'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as InvestmentRouteImport } from './routes/investment'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as BuildMyRoadmapRouteImport } from './routes/build-my-roadmap'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as OpsRouteRouteImport } from './routes/ops/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as OpsIndexRouteImport } from './routes/ops/index'
import { Route as WalksSlugRouteImport } from './routes/walks_.$slug'
import { Route as PortalRoadmapRouteImport } from './routes/portal.roadmap'
import { Route as PortalOnboardingRouteImport } from './routes/portal.onboarding'
import { Route as PortalLoginRouteImport } from './routes/portal.login'
import { Route as PortalHomeRouteImport } from './routes/portal.home'
import { Route as PortalAccessDeniedRouteImport } from './routes/portal.access-denied'
import { Route as OpsQueueRouteImport } from './routes/ops/queue'
import { Route as OpsInsightsRouteImport } from './routes/ops/insights'
import { Route as OpsHistoryRouteImport } from './routes/ops/history'
import { Route as OpsAccessEventsRouteImport } from './routes/ops/access-events'
import { Route as InsightsSlugRouteImport } from './routes/insights_.$slug'
import { Route as CheckoutRoadmapRouteImport } from './routes/checkout.roadmap'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AdminClientPortalsRouteImport } from './routes/admin.client-portals'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as OpsSubmissionsIdRouteImport } from './routes/ops/submissions.$id'
import { Route as OpsEditorIdRouteImport } from './routes/ops/editor.$id'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksBuildRoadmapContactRouteImport } from './routes/api/public/hooks/build-roadmap-contact'

const WhatWeBuildRoute = WhatWeBuildRouteImport.update({
  id: '/what-we-build',
  path: '/what-we-build',
  getParentRoute: () => rootRouteImport,
} as any)
const WalksRoute = WalksRouteImport.update({
  id: '/walks',
  path: '/walks',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentRoute = InvestmentRouteImport.update({
  id: '/investment',
  path: '/investment',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildMyRoadmapRoute = BuildMyRoadmapRouteImport.update({
  id: '/build-my-roadmap',
  path: '/build-my-roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRouteRoute = OpsRouteRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const OpsIndexRoute = OpsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpsRouteRoute,
} as any)
const WalksSlugRoute = WalksSlugRouteImport.update({
  id: '/walks_/$slug',
  path: '/walks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoadmapRoute = PortalRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => PortalRoute,
} as any)
const PortalOnboardingRoute = PortalOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PortalRoute,
} as any)
const PortalHomeRoute = PortalHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAccessDeniedRoute = PortalAccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => PortalRoute,
} as any)
const OpsQueueRoute = OpsQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => OpsRouteRoute,
} as any)
const OpsInsightsRoute = OpsInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => OpsRouteRoute,
} as any)
const OpsHistoryRoute = OpsHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => OpsRouteRoute,
} as any)
const OpsAccessEventsRoute = OpsAccessEventsRouteImport.update({
  id: '/access-events',
  path: '/access-events',
  getParentRoute: () => OpsRouteRoute,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/insights_/$slug',
  path: '/insights/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoadmapRoute = CheckoutRoadmapRouteImport.update({
  id: '/checkout/roadmap',
  path: '/checkout/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClientPortalsRoute = AdminClientPortalsRouteImport.update({
  id: '/client-portals',
  path: '/client-portals',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const OpsSubmissionsIdRoute = OpsSubmissionsIdRouteImport.update({
  id: '/submissions/$id',
  path: '/submissions/$id',
  getParentRoute: () => OpsRouteRoute,
} as any)
const OpsEditorIdRoute = OpsEditorIdRouteImport.update({
  id: '/editor/$id',
  path: '/editor/$id',
  getParentRoute: () => OpsRouteRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBuildRoadmapContactRoute =
  ApiPublicHooksBuildRoadmapContactRouteImport.update({
    id: '/api/public/hooks/build-roadmap-contact',
    path: '/api/public/hooks/build-roadmap-contact',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ops': typeof OpsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/build-my-roadmap': typeof BuildMyRoadmapRoute
  '/insights': typeof InsightsRoute
  '/investment': typeof InvestmentRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/walks': typeof WalksRoute
  '/what-we-build': typeof WhatWeBuildRoute
  '/admin/client-portals': typeof AdminClientPortalsRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/checkout/roadmap': typeof CheckoutRoadmapRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/ops/access-events': typeof OpsAccessEventsRoute
  '/ops/history': typeof OpsHistoryRoute
  '/ops/insights': typeof OpsInsightsRoute
  '/ops/queue': typeof OpsQueueRoute
  '/portal/access-denied': typeof PortalAccessDeniedRoute
  '/portal/home': typeof PortalHomeRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/onboarding': typeof PortalOnboardingRoute
  '/portal/roadmap': typeof PortalRoadmapRoute
  '/walks/$slug': typeof WalksSlugRoute
  '/ops/': typeof OpsIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/ops/editor/$id': typeof OpsEditorIdRoute
  '/ops/submissions/$id': typeof OpsSubmissionsIdRoute
  '/api/public/hooks/build-roadmap-contact': typeof ApiPublicHooksBuildRoadmapContactRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/build-my-roadmap': typeof BuildMyRoadmapRoute
  '/insights': typeof InsightsRoute
  '/investment': typeof InvestmentRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/walks': typeof WalksRoute
  '/what-we-build': typeof WhatWeBuildRoute
  '/portal': typeof PortalIndexRoute
  '/admin/client-portals': typeof AdminClientPortalsRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/checkout/roadmap': typeof CheckoutRoadmapRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/ops/access-events': typeof OpsAccessEventsRoute
  '/ops/history': typeof OpsHistoryRoute
  '/ops/insights': typeof OpsInsightsRoute
  '/ops/queue': typeof OpsQueueRoute
  '/portal/access-denied': typeof PortalAccessDeniedRoute
  '/portal/home': typeof PortalHomeRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/onboarding': typeof PortalOnboardingRoute
  '/portal/roadmap': typeof PortalRoadmapRoute
  '/walks/$slug': typeof WalksSlugRoute
  '/ops': typeof OpsIndexRoute
  '/ops/editor/$id': typeof OpsEditorIdRoute
  '/ops/submissions/$id': typeof OpsSubmissionsIdRoute
  '/api/public/hooks/build-roadmap-contact': typeof ApiPublicHooksBuildRoadmapContactRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/ops': typeof OpsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/build-my-roadmap': typeof BuildMyRoadmapRoute
  '/insights': typeof InsightsRoute
  '/investment': typeof InvestmentRoute
  '/portal': typeof PortalRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/walks': typeof WalksRoute
  '/what-we-build': typeof WhatWeBuildRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/admin/client-portals': typeof AdminClientPortalsRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/checkout/roadmap': typeof CheckoutRoadmapRoute
  '/insights_/$slug': typeof InsightsSlugRoute
  '/ops/access-events': typeof OpsAccessEventsRoute
  '/ops/history': typeof OpsHistoryRoute
  '/ops/insights': typeof OpsInsightsRoute
  '/ops/queue': typeof OpsQueueRoute
  '/portal/access-denied': typeof PortalAccessDeniedRoute
  '/portal/home': typeof PortalHomeRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/onboarding': typeof PortalOnboardingRoute
  '/portal/roadmap': typeof PortalRoadmapRoute
  '/walks_/$slug': typeof WalksSlugRoute
  '/ops/': typeof OpsIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/ops/editor/$id': typeof OpsEditorIdRoute
  '/ops/submissions/$id': typeof OpsSubmissionsIdRoute
  '/api/public/hooks/build-roadmap-contact': typeof ApiPublicHooksBuildRoadmapContactRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ops'
    | '/about'
    | '/admin'
    | '/auth'
    | '/build-my-roadmap'
    | '/insights'
    | '/investment'
    | '/portal'
    | '/sitemap.xml'
    | '/walks'
    | '/what-we-build'
    | '/admin/client-portals'
    | '/checkout/return'
    | '/checkout/roadmap'
    | '/insights/$slug'
    | '/ops/access-events'
    | '/ops/history'
    | '/ops/insights'
    | '/ops/queue'
    | '/portal/access-denied'
    | '/portal/home'
    | '/portal/login'
    | '/portal/onboarding'
    | '/portal/roadmap'
    | '/walks/$slug'
    | '/ops/'
    | '/portal/'
    | '/ops/editor/$id'
    | '/ops/submissions/$id'
    | '/api/public/hooks/build-roadmap-contact'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/build-my-roadmap'
    | '/insights'
    | '/investment'
    | '/sitemap.xml'
    | '/walks'
    | '/what-we-build'
    | '/portal'
    | '/admin/client-portals'
    | '/checkout/return'
    | '/checkout/roadmap'
    | '/insights/$slug'
    | '/ops/access-events'
    | '/ops/history'
    | '/ops/insights'
    | '/ops/queue'
    | '/portal/access-denied'
    | '/portal/home'
    | '/portal/login'
    | '/portal/onboarding'
    | '/portal/roadmap'
    | '/walks/$slug'
    | '/ops'
    | '/ops/editor/$id'
    | '/ops/submissions/$id'
    | '/api/public/hooks/build-roadmap-contact'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/ops'
    | '/about'
    | '/admin'
    | '/auth'
    | '/build-my-roadmap'
    | '/insights'
    | '/investment'
    | '/portal'
    | '/sitemap.xml'
    | '/walks'
    | '/what-we-build'
    | '/_authenticated/portal'
    | '/admin/client-portals'
    | '/checkout/return'
    | '/checkout/roadmap'
    | '/insights_/$slug'
    | '/ops/access-events'
    | '/ops/history'
    | '/ops/insights'
    | '/ops/queue'
    | '/portal/access-denied'
    | '/portal/home'
    | '/portal/login'
    | '/portal/onboarding'
    | '/portal/roadmap'
    | '/walks_/$slug'
    | '/ops/'
    | '/portal/'
    | '/ops/editor/$id'
    | '/ops/submissions/$id'
    | '/api/public/hooks/build-roadmap-contact'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  OpsRouteRoute: typeof OpsRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BuildMyRoadmapRoute: typeof BuildMyRoadmapRoute
  InsightsRoute: typeof InsightsRoute
  InvestmentRoute: typeof InvestmentRoute
  PortalRoute: typeof PortalRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WalksRoute: typeof WalksRoute
  WhatWeBuildRoute: typeof WhatWeBuildRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  CheckoutRoadmapRoute: typeof CheckoutRoadmapRoute
  InsightsSlugRoute: typeof InsightsSlugRoute
  WalksSlugRoute: typeof WalksSlugRoute
  ApiPublicHooksBuildRoadmapContactRoute: typeof ApiPublicHooksBuildRoadmapContactRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/what-we-build': {
      id: '/what-we-build'
      path: '/what-we-build'
      fullPath: '/what-we-build'
      preLoaderRoute: typeof WhatWeBuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/walks': {
      id: '/walks'
      path: '/walks'
      fullPath: '/walks'
      preLoaderRoute: typeof WalksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investment': {
      id: '/investment'
      path: '/investment'
      fullPath: '/investment'
      preLoaderRoute: typeof InvestmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build-my-roadmap': {
      id: '/build-my-roadmap'
      path: '/build-my-roadmap'
      fullPath: '/build-my-roadmap'
      preLoaderRoute: typeof BuildMyRoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/ops/': {
      id: '/ops/'
      path: '/'
      fullPath: '/ops/'
      preLoaderRoute: typeof OpsIndexRouteImport
      parentRoute: typeof OpsRouteRoute
    }
    '/walks_/$slug': {
      id: '/walks_/$slug'
      path: '/walks/$slug'
      fullPath: '/walks/$slug'
      preLoaderRoute: typeof WalksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/roadmap': {
      id: '/portal/roadmap'
      path: '/roadmap'
      fullPath: '/portal/roadmap'
      preLoaderRoute: typeof PortalRoadmapRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/onboarding': {
      id: '/portal/onboarding'
      path: '/onboarding'
      fullPath: '/portal/onboarding'
      preLoaderRoute: typeof PortalOnboardingRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/login': {
      id: '/portal/login'
      path: '/login'
      fullPath: '/portal/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/home': {
      id: '/portal/home'
      path: '/home'
      fullPath: '/portal/home'
      preLoaderRoute: typeof PortalHomeRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/access-denied': {
      id: '/portal/access-denied'
      path: '/access-denied'
      fullPath: '/portal/access-denied'
      preLoaderRoute: typeof PortalAccessDeniedRouteImport
      parentRoute: typeof PortalRoute
    }
    '/ops/queue': {
      id: '/ops/queue'
      path: '/queue'
      fullPath: '/ops/queue'
      preLoaderRoute: typeof OpsQueueRouteImport
      parentRoute: typeof OpsRouteRoute
    }
    '/ops/insights': {
      id: '/ops/insights'
      path: '/insights'
      fullPath: '/ops/insights'
      preLoaderRoute: typeof OpsInsightsRouteImport
      parentRoute: typeof OpsRouteRoute
    }
    '/ops/history': {
      id: '/ops/history'
      path: '/history'
      fullPath: '/ops/history'
      preLoaderRoute: typeof OpsHistoryRouteImport
      parentRoute: typeof OpsRouteRoute
    }
    '/ops/access-events': {
      id: '/ops/access-events'
      path: '/access-events'
      fullPath: '/ops/access-events'
      preLoaderRoute: typeof OpsAccessEventsRouteImport
      parentRoute: typeof OpsRouteRoute
    }
    '/insights_/$slug': {
      id: '/insights_/$slug'
      path: '/insights/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/roadmap': {
      id: '/checkout/roadmap'
      path: '/checkout/roadmap'
      fullPath: '/checkout/roadmap'
      preLoaderRoute: typeof CheckoutRoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/client-portals': {
      id: '/admin/client-portals'
      path: '/client-portals'
      fullPath: '/admin/client-portals'
      preLoaderRoute: typeof AdminClientPortalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/ops/submissions/$id': {
      id: '/ops/submissions/$id'
      path: '/submissions/$id'
      fullPath: '/ops/submissions/$id'
      preLoaderRoute: typeof OpsSubmissionsIdRouteImport
      parentRoute: typeof OpsRouteRoute
    }
    '/ops/editor/$id': {
      id: '/ops/editor/$id'
      path: '/editor/$id'
      fullPath: '/ops/editor/$id'
      preLoaderRoute: typeof OpsEditorIdRouteImport
      parentRoute: typeof OpsRouteRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/build-roadmap-contact': {
      id: '/api/public/hooks/build-roadmap-contact'
      path: '/api/public/hooks/build-roadmap-contact'
      fullPath: '/api/public/hooks/build-roadmap-contact'
      preLoaderRoute: typeof ApiPublicHooksBuildRoadmapContactRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface OpsRouteRouteChildren {
  OpsAccessEventsRoute: typeof OpsAccessEventsRoute
  OpsHistoryRoute: typeof OpsHistoryRoute
  OpsInsightsRoute: typeof OpsInsightsRoute
  OpsQueueRoute: typeof OpsQueueRoute
  OpsIndexRoute: typeof OpsIndexRoute
  OpsEditorIdRoute: typeof OpsEditorIdRoute
  OpsSubmissionsIdRoute: typeof OpsSubmissionsIdRoute
}

const OpsRouteRouteChildren: OpsRouteRouteChildren = {
  OpsAccessEventsRoute: OpsAccessEventsRoute,
  OpsHistoryRoute: OpsHistoryRoute,
  OpsInsightsRoute: OpsInsightsRoute,
  OpsQueueRoute: OpsQueueRoute,
  OpsIndexRoute: OpsIndexRoute,
  OpsEditorIdRoute: OpsEditorIdRoute,
  OpsSubmissionsIdRoute: OpsSubmissionsIdRoute,
}

const OpsRouteRouteWithChildren = OpsRouteRoute._addFileChildren(
  OpsRouteRouteChildren,
)

interface AdminRouteChildren {
  AdminClientPortalsRoute: typeof AdminClientPortalsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminClientPortalsRoute: AdminClientPortalsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PortalRouteChildren {
  PortalAccessDeniedRoute: typeof PortalAccessDeniedRoute
  PortalHomeRoute: typeof PortalHomeRoute
  PortalLoginRoute: typeof PortalLoginRoute
  PortalOnboardingRoute: typeof PortalOnboardingRoute
  PortalRoadmapRoute: typeof PortalRoadmapRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAccessDeniedRoute: PortalAccessDeniedRoute,
  PortalHomeRoute: PortalHomeRoute,
  PortalLoginRoute: PortalLoginRoute,
  PortalOnboardingRoute: PortalOnboardingRoute,
  PortalRoadmapRoute: PortalRoadmapRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  OpsRouteRoute: OpsRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BuildMyRoadmapRoute: BuildMyRoadmapRoute,
  InsightsRoute: InsightsRoute,
  InvestmentRoute: InvestmentRoute,
  PortalRoute: PortalRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WalksRoute: WalksRoute,
  WhatWeBuildRoute: WhatWeBuildRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  CheckoutRoadmapRoute: CheckoutRoadmapRoute,
  InsightsSlugRoute: InsightsSlugRoute,
  WalksSlugRoute: WalksSlugRoute,
  ApiPublicHooksBuildRoadmapContactRoute:
    ApiPublicHooksBuildRoadmapContactRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
