/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatWeBuildRouteImport } from './routes/what-we-build'
import { Route as InvestmentRouteImport } from './routes/investment'
import { Route as IndexRouteImport } from './routes/index'

const WhatWeBuildRoute = WhatWeBuildRouteImport.update({
  id: '/what-we-build',
  path: '/what-we-build',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentRoute = InvestmentRouteImport.update({
  id: '/investment',
  path: '/investment',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/investment': typeof InvestmentRoute
  '/what-we-build': typeof WhatWeBuildRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/investment': typeof InvestmentRoute
  '/what-we-build': typeof WhatWeBuildRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/investment': typeof InvestmentRoute
  '/what-we-build': typeof WhatWeBuildRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/investment' | '/what-we-build'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/investment' | '/what-we-build'
  id: '__root__' | '/' | '/investment' | '/what-we-build'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InvestmentRoute: typeof InvestmentRoute
  WhatWeBuildRoute: typeof WhatWeBuildRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/what-we-build': {
      id: '/what-we-build'
      path: '/what-we-build'
      fullPath: '/what-we-build'
      preLoaderRoute: typeof WhatWeBuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investment': {
      id: '/investment'
      path: '/investment'
      fullPath: '/investment'
      preLoaderRoute: typeof InvestmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InvestmentRoute: InvestmentRoute,
  WhatWeBuildRoute: WhatWeBuildRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
